kptdev/krm-functions-catalog

.github/workflows/ci.yaml, site/deploy.sh, site/themes/docsy/userguide/deploy.sh
Create this pull request from a feature branch since creating it from my fork's branch made the workflow fail
=> Add CI using Github Actions

functions/ts/package-lock.json, functions/ts/package.json, tests/e2e.sh
Tested e2e script by running locally
=> Fix e2e script and update version for release

functions/ts/build/kustomize_build.Dockerfile, functions/ts/package-lock.json, functions/ts/package.json, functions/ts/src/istioctl_analyze.ts, functions/ts/src/kubeval_test.ts, functions/ts/src/kustomize_build.ts, functions/ts/src/kustomize_build_run.ts, functions/ts/src/kustomize_build_test.ts, tests/e2e.sh
- Update kpt functions to 0.14.2
- Add kustomize build function
- Refactor helm template and istioctl analyze functions to use getFunctionConfigMap
Fixes GoogleContainerTools/kpt#576
=> Add kustomize build function

functions/ts/build/kustomize_build.Dockerfile
Link to https://github.com/GoogleContainerTools/kpt/issues/791
=> fix(fn.kustomize.build): provide git binary to allow remote fetch

tests/e2e.sh
Related to GoogleContainerTools/kpt#791
=> Add e2e test for kustomize building remote resources

functions/ts/build/helm_template.Dockerfile, functions/ts/build/istioctl_analyze.Dockerfile, functions/ts/build/kustomize_build.Dockerfile
Fixes GoogleContainerTools/kpt#879
=> Update default CLI versions being used in catalog functions

functions/ts/src/helm_template.ts, functions/ts/src/istioctl_analyze.ts, tests/istioctl_analyze.sh
Link GoogleContainerTools/kpt#823
=> Fix functions interpreting string args as booleans

functions/ts/package-lock.json, functions/ts/package.json, tests/kubeval.sh, tests/suggest_psp.sh
Will release ts functions 0.1.1
=> Update sdk version

examples/sops/README.md, functions/ts/package-lock.json, functions/ts/package.json, functions/ts/src/sops.ts
Minor fixes to sops README
Update gcr image in sops usage
Update version
=> Update version for release

examples/istioctl-analyze/README.md, examples/kubeval/README.md, examples/suggest-psp/README.md
Fixes https://github.com/GoogleContainerTools/kpt/issues/983
=> Remove --results-dir from examples

CONTRIBUTING.md, README.md, docs/index.html
Addresses part of https://github.com/GoogleContainerTools/kpt/issues/1066
=> Remove broken function catalog links.

.github/workflows/ci.yaml, tests/annotate_config.sh, tests/common.sh, tests/helm_template.sh, tests/istioctl_analyze.sh, tests/kubeval.sh, tests/kustomize_build.sh, tests/set_namespace_go.sh, tests/set_namespace_starlark.sh, tests/sops.sh, tests/suggest_psp.sh
Fixes https://github.com/GoogleContainerTools/kpt/issues/976
=> Convert kustomize build docker run tests and remove NODOCKER option

CONTRIBUTING.md, examples/helm-template/README.md
Fixes https://github.com/GoogleContainerTools/kpt/issues/960
=> Add output to helm-template example.

MAINTAINERS
=> add Donny Xia to maintainer

examples/kubeval/fn-config.yaml, tests/kubeval.sh
The error is caused by `network` field in latest kpt.
=> fix CI failure

examples/helm-template/local-configs/fn-config.yaml
The helm template example need to be updated to release latest images.
=> fix release e2e test

MAINTAINERS
Added myself and removed Prachi as Frank requested. Then sort it by alphabetical order.
=> add @mengqiy in MAINTAINERS file

docs/index.html
https://github.com/GoogleContainerTools/kpt/issues/1263
=> remove docs

examples/sops/README.md, examples/sops/local-configs/function.yaml, examples/sops/local-configs/to-decrypt.yaml, examples/sops/local-configs/to-encrypt.yaml, functions/ts/build/sops.Dockerfile, functions/ts/package-lock.json, functions/ts/package.json, functions/ts/src/sops.ts, tests/sops.sh
Added support for encrypt operation for the function.
That extends the functionality and list of potential use-cases for this function:
it's possible to encrypt the newly generated secrets or rotate them.
The description, set of examples and e2e tests were update accordingly
=> Encryption support for sops function

functions/go/set-namespace/go.mod, functions/go/set-namespace/go.sum
fix https://github.com/GoogleContainerTools/kpt/issues/1305
=> update version of kustomize/api

tests/helm_inflator.sh
similar to #130 .
Need to refactor after e2e test driver is ready.
=> fix helm e2e test

functions/ts/sops/src/sops.ts
This change just introduces some degree of flexibility to control error handling
This flag allows to skip failure if
some documents were not decrypted/encrypted.
This may be useful for serveral use-cases:
1. several attempts to decrypt with different
secrets sets: use the chain of sops fn
and set cmd-tolerate-failures: false in
all of them except the last one. the
last one will fail if there are some
undecrypted/unencrypted docs left.
2. ability to use that documents values
for futher processing for people
who don't have secrets to decrypt.
May be useful for debugging perposes.
Also adjusted the code in a way
so the fucntion doesn nothing if
cmd is unknown: 'no-op' behavior.
=> SOPS: Adding cmd-tolerate-failures flag

functions/go/set-namespace/Dockerfile, functions/ts/helm-inflator/build/helm_inflator.Dockerfile, functions/ts/istioctl-analyze/build/istioctl_analyze.Dockerfile, functions/ts/kubeval/build/kubeval.Dockerfile, functions/ts/sops/build/sops.Dockerfile
fixes: https://github.com/GoogleContainerTools/kpt/issues/1247
=> pin the base images versions

functions/go/set-annotation/main.go, functions/go/set-label/main.go, functions/go/set-namespace/main.go, tests/set-annotation-empty-list/.expected/config.yaml, tests/set-annotation-empty-list/.expected/results.yaml, tests/set-annotation-empty-list/.krmignore, tests/set-annotation-empty-list/fn-config.yaml, tests/set-annotation-empty-list/resources.yaml, tests/set-label-empty-list/.expected/config.yaml, tests/set-label-empty-list/.expected/results.yaml, tests/set-label-empty-list/.krmignore, tests/set-label-empty-list/fn-config.yaml, tests/set-label-empty-list/resources.yaml, tests/set-namespace-invalid-input/.expected/config.yaml, tests/set-namespace-invalid-input/.expected/results.yaml, tests/set-namespace-invalid-input/.krmignore, tests/set-namespace-invalid-input/fn-config.yaml, tests/set-namespace-invalid-input/resources.yaml
Also updated the function to return errors through fn framework.
close https://github.com/GoogleContainerTools/kpt/issues/1488
=> Add tests for function failures

scripts/function-release.sh
I have restructured the layout of the repo recently.
The release script is out-of-date.
=> update release script

examples/runtime/starlark/simple/README.md
Update README content to match the starlark source code.
=> update the starlark example

functions/go/apply-setters/Dockerfile, functions/go/search-replace/Dockerfile
This PR is to add ENTRYPOINT for search-replace and apply-setters and make them consistent with other functions.
fixes: https://github.com/GoogleContainerTools/kpt/issues/1564
=> Add ENTRYPOINT for search-replace and apply-setters

functions/go/apply-setters/README.md, functions/go/apply-setters/generated/docs.go
This PR is to update the readme of apply setters with version v0.1 in release branch.
=> Update image in Apply setters readme

functions/go/search-replace/README.md, functions/go/search-replace/generated/docs.go
This PR is to update the image version for Search and Replace in Readme of v0.1
=> Search replace docs readme v0.1

scripts/generate_catalog/generate_catalog.go
Fixes https://github.com/GoogleContainerTools/kpt/issues/1831
=> Do not process hidden function versions.

functions/ts/kubeval/README.md, functions/ts/kubeval/src/kubeval.ts
=> add usage doc for kubeval (#257)

functions/go/search-replace/README.md, functions/go/search-replace/generated/docs.go
This PR is to fix type in Search Replace Readme in v0.1
=> Fix type search-replace v0.1

functions/ts/_template/README.md
TS counterpart of https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/functions/go/_template/README.md
=> add usage doc template for TS functions

examples/_template/README.md, examples/apply-setters/simple/README.md, examples/contrib/analyze-istio/README.md, examples/contrib/inflate-helm-chart/README.md, examples/contrib/sops/README.md, examples/enforce-gatekeeper/invalid-configmap/README.md, examples/enforce-gatekeeper/warning-only/README.md, examples/ensure-name-substring/advanced/README.md, examples/ensure-name-substring/prefix/README.md, examples/ensure-name-substring/suffix/README.md, examples/kubeval/simple/README.md, examples/search-replace/simple/README.md, examples/set-annotations/advanced/README.md, examples/set-annotations/simple/README.md, examples/set-labels/advanced/README.md, examples/set-labels/simple/README.md, examples/set-namespace/advanced/README.md, examples/set-namespace/simple/README.md, examples/starlark/simple/README.md
Partially address https://github.com/GoogleContainerTools/kpt/issues/1825
=> fix README styling for examples

functions/go/apply-setters/applysetters/apply_setters.go, functions/go/apply-setters/applysetters/apply_setters_test.go
This PR is to use placeholder string instead of setter names for regex matching to resolve named capture groups. Setter names might have special characters which might interfere with regex special characters.
Fixes issue https://github.com/GoogleContainerTools/kpt/issues/1940
=> Use placeholder instead of setter names for regex matching

examples/kubeval/simple/.expected/results.yaml, examples/kubeval/simple/resources.yaml, functions/ts/kubeval/src/kubeval.ts
fixes: https://github.com/GoogleContainerTools/kpt/issues/1938
=> improve error message for kubeval when encounter unknown CRDs

scripts/generate_catalog/generate_catalog.go
=> Use image paths as names for landing page.

functions/go/search-replace/main.go, tests/search-replace/no-results/simple/.expected/config.yaml, tests/search-replace/no-results/simple/.expected/results.yaml, tests/search-replace/no-results/simple/.krmignore, tests/search-replace/no-results/simple/fn-config.yaml, tests/search-replace/no-results/simple/resources.yaml
Log message for no results for input search criteria.
=> Log message for no search results

examples/apply-setters/simple/README.md, examples/search-replace/create-setters/.expected/config.yaml, examples/search-replace/create-setters/.expected/diff.patch, examples/search-replace/create-setters/.krmignore, examples/search-replace/create-setters/README.md, examples/search-replace/create-setters/fn-config.yaml, examples/search-replace/create-setters/resources.yaml, functions/go/apply-setters/README.md, functions/go/search-replace/metadata.yaml
This PR is to add an e2e example for creating setters using `search-replace` function.
=> Create setters example

functions/go/apply-setters/applysetters/apply_setters.go, functions/go/apply-setters/applysetters/apply_setters_test.go
This PR is to better handle empty values in apply setters.
@yhrn The two tests should summarize the way empty values are handled.
=> Better handle empty values for apply-setters

functions/go/fix/fixpkg/fix.go, testdata/fix/nginx-v1alpha2/Kptfile, testdata/fix/nginx-v1alpha2/hello-world/Kptfile
This PR is to add the setters first to the pipeline while fixing packages.
https://github.com/GoogleContainerTools/kpt/issues/2094
=> fix function: Add setters first to the pipeline

.github/workflows/checkSite.yml, scripts/generate_catalog/generate_catalog.go
Fixes https://github.com/GoogleContainerTools/kpt/issues/2112
=> Skip missing and contributed funcs in site.

functions/go/apply-setters/README.md, functions/go/apply-setters/generated/docs.go, functions/go/fix/generated/docs.go, functions/go/search-replace/README.md, functions/go/search-replace/generated/docs.go
Update README docs for functions to be compatible with 1.0.
=> Update apply-setters, search-replace, docs for 1.0 compatibility

site/index.html
Fixes https://github.com/GoogleContainerTools/kpt/issues/2132
Partially addresses https://github.com/GoogleContainerTools/kpt/issues/2128
Imports main site style into catalog.
=> Add GH widget to the bottom of function docs.

site/index.html, site/sidebar.md
Fixes https://github.com/GoogleContainerTools/kpt/issues/2220
=> Open external links in new tab.

examples/search-replace/simple/README.md
=> fix a minor typo

site/index.html
Fixes https://github.com/GoogleContainerTools/kpt/issues/2128
=> Add copy button to catalog.

site/index.html
Fixes https://github.com/GoogleContainerTools/kpt/issues/2267
=> Make edit button redirect to the main branch.

scripts/generate_catalog/generate_catalog.go
Fixes https://github.com/GoogleContainerTools/kpt/issues/2250
Avoids assuming things about the directories between "`examples`"  and `exampleName`
=> Make catalog generation script more generic.

functions/go/Makefile, scripts/function-release.sh
We stop check in generated files in #401.
We need to update some release scripts (This PR)
=> fix release script

functions/go/starlark/go.mod, functions/go/starlark/go.sum, functions/go/starlark/third_party/README.md, functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/context.go, functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/doc.go, functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/starlark.go
Preparation for https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/473
=> import kyaml starlark code

functions/go/starlark/config.go, functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/starlark.go, tests/starlark/preserve-id-annotations/.expected/diff.patch, tests/starlark/preserve-id-annotations/.expected/exec.sh, tests/starlark/preserve-id-annotations/.krmignore, tests/starlark/preserve-id-annotations/app.yaml, tests/starlark/preserve-id-annotations/fn-config.yaml
Fixes: https://github.com/GoogleContainerTools/kpt/issues/2382
=> Fix starlark function to not drop id annotation

VERSIONING.md
Fixes: https://github.com/GoogleContainerTools/kpt/issues/1901
=> Document semver, backward compatibility and best practices

examples/search-replace-create-setters/.expected/exec.sh, examples/search-replace-create-setters/README.md, examples/search-replace-simple/Kptfile, examples/search-replace-simple/README.md, functions/go/search-replace/README.md, functions/go/search-replace/metadata.yaml
This PR updates the docs of search-replace function to point to v0.2.
=> Update search-replace docs for v0.2

examples/format-imperative/README.md, functions/go/format/README.md, functions/go/format/metadata.yaml
This PR is to add note to format docs about the usage with new beta.2+
=> Deprecate Format docs

scripts/generate_catalog/generate_catalog.go
Fixes https://github.com/GoogleContainerTools/kpt/issues/2430
=> Add support for GCP-tagged functions.

.github/workflows/checkSite.yml, .github/workflows/firebase-hosting-merge.yml
Fixes https://github.com/GoogleContainerTools/kpt/issues/2446
=> Merge gob branch with master before collecting functions.

functions/go/list-setters/main.go, tests/list-setters/no-matches-error/.expected/config.yaml, tests/list-setters/no-matches-error/.expected/results.yaml, tests/list-setters/no-matches-error/.krmignore, tests/list-setters/no-matches-error/resources.yaml
similar to https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/546, warn and exit if no setters found
=> fix(list-setters): do not error for empty setters

examples/render-helm-chart-kustomize-inline-values/.expected/diff.patch
Fix a CI failure for the render-helm-chart-kustomize-inline-values example
=> fix kustomize helm inflator CI failure

.github/workflows/checkSite.yml, .github/workflows/firebase-hosting-merge.yml, scripts/check-site.sh
Port the change from https://github.com/GoogleContainerTools/kpt/pull/2503/files
=> ci: re-enable checkSite CI

site/index.html
Similar to https://github.com/GoogleContainerTools/kpt/pull/2522.
In a later PR, I will update catalog site to use the same sidebar as kpt repo.
=> Pin docsify-themeable to 0.8.4

functions/go/ensure-name-substring/main.go
Fixes: https://github.com/GoogleContainerTools/kpt/issues/2317
=> fix: stop printing error message twice

.github/workflows/checkSite.yml
checkSite CI is complaining about something, but I can't figure out what it is.
This PR disables it temporarily.
=> disable checkSite CI

scripts/generate_catalog/generate_catalog.go, site/index.html
Reverts GoogleContainerTools/kpt-functions-catalog#666
=> Revert "Site examples patch version"

scripts/update_function_docs/function_release.go
This commit adds support for updating the function docs for:
- Kptfile
- metadata.yaml
The Kptfile commonly contains the image for the given function release,
so this change will ensure that images get updated for a release.
The metadata.yaml commonly contains references to github URLs which
direct to paths within a function release. A new replaceGithubURLs
method is added which ensures the URL points to the correct ref for the
release branch.
Issues: GoogleContainerTools/kpt#2632
=> docs: update-function-docs Kptfile/metadata.yaml

site/index.html
Reverts GoogleContainerTools/kpt-functions-catalog#731
=> Revert "docs: include v in version dropdown for site"

site/index.html
Reverts GoogleContainerTools/kpt-functions-catalog#723
=> Revert "docs: Dynamically render latest image tag in docs"

site/index.html
#731 was rolled back by mistake in #732.
This PR is rolling back the the rollback PR.
=> Revert "Revert "docs: include v in version dropdown for site""

contrib/examples/generate-kpt-pkg-docs-simple/.expected/diff.patch, contrib/functions/go/generate-kpt-pkg-docs/docs/generate.go, contrib/functions/go/generate-kpt-pkg-docs/docs/generate_test.go
An invalid quote was added to the usage template
=> fix(docs-fn): invalid quoting in usage section

functions/go/set-namespace/transformer/namespace.go
RoleBinding is namespace scoped, but it can bind other namespace's ServiceAccount to the namespace it lives. When replacing a namespace, if the rolebinding's own namespace matches the target namespace, itself should be updated, if its subjects namespace matches the target namespace (even if itself is in another namespace), the subject's namespace should be updated.
The code change merges the ClusterRoleBinding and Rolebinding's `subjects` handling together, and include `RoleBinding` itself to the `metadata.namespace` updates.
=> feat: set-namespace special treatment for RoleBinding

site/index.html
This PR refers to the new logo in kpt repo. Better to be merged after https://github.com/GoogleContainerTools/kpt/pull/3107
=> update new logo and color

examples/set-namespace-depends-on/Kptfile, examples/set-namespace-depends-on/README.md, examples/set-namespace-kpt-package-context/Kptfile, examples/set-namespace-kpt-package-context/README.md, examples/set-namespace-simple/Kptfile, examples/set-namespace-simple/README.md
Merge directly since this is not to masterMerge directly since this is not to master
=> docs: Update tags for go/set-namespace/v0.4.0 (#846)

functions/ts/kubeval/build/kubeval.Dockerfile, functions/ts/kubeval/openapi/README.md, functions/ts/kubeval/openapi/kptfile.json, functions/ts/kubeval/package.json
Uses the openapi generated in https://github.com/GoogleContainerTools/kpt-functions-sdk/pull/577
=> combine kptfile openapi schema in kubeval

functions/ts/kubeval/openapi/README.md
Openapi for kcc types is also updated.
Addresses b/222487036
=> update builtin k8s openapi to v1.22

build/docker/go/Dockerfile, build/docker/go/defaults.env, build/docker/ts/Dockerfile, build/docker/ts/defaults.env, contrib/functions/ts/analyze-istio/build/analyze_istio.Dockerfile, contrib/functions/ts/sops/build/sops.Dockerfile, functions/go/render-helm-chart/Dockerfile, functions/ts/kubeval/build/kubeval.Dockerfile, scripts/docker.sh
This change consolidates the base images used by Dockerfiles of the same
language. This is intended to make it easier to manage the base images
used by the various functions.
=> ci: consolidate base image definitions

functions/go/generate-kpt-pkg-docs/go.mod, functions/go/generate-kpt-pkg-docs/main.go
fixes https://github.com/GoogleContainerTools/kpt/issues/3227
=> fix: update generate-kpt-pkg-docs go mod path

functions/go/export-terraform/README.md, functions/go/export-terraform/terraformgenerator/network.go, functions/go/export-terraform/terraformgenerator/templates/projects.tf, functions/go/export-terraform/terraformgenerator/terraform_generator.go, functions/go/export-terraform/testdata/multi-network/input/net1/sharedVPC.yaml, functions/go/export-terraform/testdata/multi-network/input/net2/sharedVPC.yaml, functions/go/export-terraform/testdata/multi-network/tf/projects.tf, functions/go/export-terraform/testdata/network/input/sharedVPC.yaml, functions/go/export-terraform/testdata/network/tf/projects.tf
This adds support for identifying Shared VPC host projects and enabling it via Project Factory.
b/244356998
=> feat: support svpc host project in export-terraform

.github/workflows/firebase-hosting-merge.yml
Reverts GoogleContainerTools/kpt-functions-catalog#936
=> Revert "bump CI node.js to 6"

.github/workflows/firebase-hosting-merge.yml
Reverts GoogleContainerTools/kpt-functions-catalog#935
=> Revert "docs: Update tags for go/set-labels/v0.2.0 (#931)"

functions/ts/generate-folders/README.md
=>  just a simple doco fix

functions/go/render-helm-chart/third_party/sigs.k8s.io/kustomize/api/builtins/HelmChartInflationGenerator.go
This fixes the issue reported by https://kubernetes.slack.com/archives/C0155NSPJSZ/p1677612509818639.
In the upstream kustomize helm plugin, we recently updated how we parse the output of running `helm template` due to some user-reported issues. This PR updates the render-helm-chart function to pick up that change from the upstream kustomize builtin. I have verified that the reported issue is fixed with this change, which confirms that the issue was due to some incorrect parsing logic.
Reproduction steps:
Build `render-helm-chart` locally. Then create an empty kpt package and run the local function.
```
$ go install .
$ mkdir foo; kpt pkg init foo
$ kpt fn eval foo --exec=render-helm-chart --results-dir . --output ./output -- name=kube-prometheus-stack …
```
=> fix issue with parsing helm output
