functions/starlark/set_namespace.star
tests/e2e.sh

Users currently have no way to set the namespace of all resources when using Config Sync with unstructured layout.
This function provides a way for users to easily set the namespace field.
Fixes GoogleContainerTools/kpt#683

Set namespace function and e2e test

---

functions/ts/build/helm_template.Dockerfile
functions/ts/build/istioctl_analyze.Dockerfile
functions/ts/build/kubeval.Dockerfile
functions/ts/build/kustomize_build.Dockerfile

Probably this will be a helpful thing:
This change allows to override the value
of the component versions, e.g.[1].
According to [2] ENV values persist in
Dockerfile and ARG can be redefinded with
--build-arg parameter, that probably would
be great to do without changes in the
Dockerfile itself.
[1]
functions/ts$ docker build -f build/kustomize_build.Dockerfile --build-arg KUSTOMIZE_VERSION=v3.8.0 ./
[2]
https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

ARG instead of EVN to set component version

---

functions/go/set-namespace/main.go

When the flag is set to false, this function should fail and return a list of cluster-scoped resources.

Add --allow-cluster-scoped flag whose default value is true

---

functions/ts/src/helm_template.ts

Clarify that chart name is optional and will have a default value of RELEASE-NAME if none is provided.

Update helm template usage

---

functions/ts/build/kustomize_build.Dockerfile

This is to make docker-in-docker possible for kustomize_build fn:
kustomize build command may work with kpt-function
based plugins, but in order to make it work
kustomize_build function must contain docker-cli
to be able to run docker in docker.

Added docker-cli package to kustomize_build fn

---

tests/helm_inflator.sh

We haven't release the helm-inflator image so we have to use helm-template function in examples.

fix ci issue

---

functions/ts/build/sops.Dockerfile

some usefull features were added
e.g.: --unencrypted-regex
usage example:
--unencrypted-regex '^(kind|apiVersion|group|metadata)$'
see
https://github.com/mozilla/sops/releases/tag/v3.6.1
unencrypted-regex wasn't supported in the
previous versions and if someone uses it
sops krm-function with older binary won't be able
to decrypt that.
PS
build is failing, but I guess just need to rebase after https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/121 is merged

Updated sops binary to the latest release 3.6.1

---

functions/ts/src/helm_inflator.ts
functions/ts/src/helm_inflator_test.ts
tests/helm_inflator.sh

`zookeeper` chart used in the test is updated to include a dependency. `helm-inflator` needs to update the dependency before running `template` command.

add dependency update for helm inflator

---

functions/ts/helm-inflator/src/helm_inflator.ts
tests/helm-inflator/fn-config.yaml

Fix CI. Now the helm-inflator e2e test will pin to a specific version of chart which can avoid issues from chart updating.

add option to specify remote chart version

---

.github/workflows/ci.yaml
CONTRIBUTING.md
RELEASING.md
examples/helm-inflator/README.md
examples/helm-inflator/local-configs/fn-config.yaml
examples/istioctl-analyze/fn-config.yaml
examples/kubeval/fn-config.yaml
examples/set-namespace/.expected/diff.patch
examples/set-namespace/functions/fn-config.yaml
examples/sops/local-configs/function.yaml
functions/go/Makefile
functions/ts/Makefile
functions/ts/helm-inflator/src/helm_inflator.ts
functions/ts/istioctl-analyze/src/istioctl_analyze.ts
functions/ts/sops/src/sops.ts
scripts/go-function-release.sh
scripts/ts-function-release.sh
tests/helm-inflator/fn-config.yaml
tests/sops.sh

We use `unstable` as image tag name until we have stable release for these kpt functions.
This PR also starts to use gcr.io/kpt-fn and gcr.io/kpt-fn-contrib repos for the functions that live in this repo.

Split curated and contrib functions in the build and release

---

examples/set-annotation/.expected/diff.patch
examples/set-annotation/functions/fn-config.yaml
examples/set-label/.expected/diff.patch
examples/set-label/functions/fn-config.yaml
functions/go/set-annotation/main.go
functions/go/set-label/main.go

We should not repeat ourselves when the top level already has "annotatioins" or "labels".

Update json|yaml tag naming

---

functions/go/set-annotation/Dockerfile
functions/go/set-label/Dockerfile
functions/go/set-namespace/Dockerfile
functions/go/starlark/Dockerfile

Also tweak Dockerfile to speed up build speed by avoiding repeatly downloading go modules.
This will make implementing `kpt fn doc` command easier. We don't need to specify the CMD. It now becomes `docker run <image-name> --help`.

use Entrypoint instead of CMD in Dockerfiles

---

examples/contrib/helm-inflator/README.md

Since `kpt` functions run as `nobody`, the commands as listed result in `Error: validation: chart.metadata is required`, unless your directory is world-readable.

Run helm-inflator as current user

---

examples/apply-setters/simple/README.md
examples/apply-setters/simple/fn-config.yaml
examples/search-replace/simple/README.md
examples/search-replace/simple/fn-config.yaml
functions/go/apply-setters/README.md
functions/go/apply-setters/generated/docs.go
functions/go/search-replace/README.md
functions/go/search-replace/generated/docs.go
tests/e2etest/e2e_test.go

This PR is to clean-up the docs for search-replace and apply-setters. The docs are written for invoking functions with kpt v1 binary.

Clean up search-replace and apply-setters docs

---

.gitignore
examples/kubeval/simple/.expected/results.yaml
examples/kubeval/simple/README.md
examples/kubeval/simple/fn-config.yaml
functions/ts/kubeval/build/kubeval.Dockerfile
functions/ts/kubeval/src/kubeval.ts
functions/ts/kubeval/third_party/github.com/instrumenta/openapi2jsonschema/openapi2jsonschema/command.py
functions/ts/kubeval/third_party/github.com/instrumenta/openapi2jsonschema/openapi2jsonschema/test_command.py

fixes: https://github.com/GoogleContainerTools/kpt/issues/1621

Make kubeval hermetic

---

scripts/generate_catalog/generate_catalog.go

Per style guide: `kpt` not `KPT`.

Update the catalog title

---

scripts/verify-docs.py

GITHUB_REF is not working as I expected. I use GITHUB_BASE_REF now.
Ref: https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables

use GITHUB_BASE_REF env var

---

site/index.html
site/sidebar.md

Addresses https://github.com/GoogleContainerTools/kpt/issues/1717 and https://github.com/GoogleContainerTools/kpt/issues/1825 for catalog.kpt.dev
Add favicon.
Top `kpt` links to overview page.
External links open to kpt.dev
Match styling to kpt.dev

Fix miscellaneous styling issues.

---

functions/go/apply-setters/applysetters/apply_setters.go
functions/go/apply-setters/applysetters/apply_setters_test.go
scripts/generate_catalog/generate_catalog.go

This PR escapes the pattern string so that pattern matching works even if the current value contains any regular expressions.

Escape regex characters in setter pattern

---

functions/go/apply-setters/applysetters/apply_setters.go
functions/go/apply-setters/applysetters/apply_setters_test.go

This PR is to handle empty values cases for apply-setters function.

Apply setters empty values checks

---

site/index.html

Fixes https://github.com/GoogleContainerTools/kpt/issues/1717
Brightens the color of the site theme to match the logo background.

Add kpt logo to catalog site.

---

examples/apply-setters/simple/.expected/results.yaml
functions/go/apply-setters/applysetters/apply_setters.go
functions/go/apply-setters/applysetters/apply_setters_test.go
functions/go/apply-setters/applysetters/walk.go
functions/go/apply-setters/main.go
tests/apply-setters/no-matches-error/.expected/config.yaml
tests/apply-setters/no-matches-error/.expected/results.yaml
tests/apply-setters/no-matches-error/.krmignore
tests/apply-setters/no-matches-error/fn-config.yaml
tests/apply-setters/no-matches-error/resources.yaml

This PR is to add results for `apply-setters` function.
```
➜  simple k fn eval --image gcr.io/kpt-fn/apply-setters:unstable --fn-config ./fn-config.yaml
[RUNNING] "gcr.io/kpt-fn/apply-setters:unstable"
[PASS] "gcr.io/kpt-fn/apply-setters:unstable"
Results:
[INFO] Set field value to "my-new-map" in file "resources.yaml" in field "metadata.name"
[INFO] Set field value to "- prod\n- stage\n" in file "resources.yaml" in field "environments"
```

Results for apply-setters

---

README.md

This adds an "Open an Issue" link to the function catalog README. Issues can not be opened against this project so a link is provided to help direct people to an area for raising issues and creating work items for the project.

Add "open an issue" link to README

---

scripts/generate_catalog/generate_catalog.go

Partially addresses https://github.com/GoogleContainerTools/kpt/issues/2076

Switch back to function name in catalog.

---

examples/fix/simple/.expected/config.yaml
functions/go/fix/fixpkg/fix.go
functions/go/fix/main.go

This PR is to make fix function idempotent and not throw an error if the package is already fixed.

Make fix function idempotent

---

site/index.html

Fixes https://github.com/GoogleContainerTools/kpt/issues/2076 by adding sidebar button back to mobile.

Fix offset border for GH widget.

---

examples/ensure-name-substring-imperative/README.md

This addresses a mismatch between the argument to the function and the expected result.

Fix ensure-name-substring imperative example

---

examples/create-setters-simple/README.md
functions/go/create-setters/README.md
functions/go/create-setters/createsetters/create_setters.go
functions/go/create-setters/createsetters/create_setters_test.go

This pr adds the following changes to `create-setters`
* Doesn't add the comments to the scalar values with multiple lines.
* Matches the longest length matched setter value to set the comment if two or more setter values have the same substrings.
e.g., Input resource
```yaml
apiVersion: v1
kind: Deployment
metadata:
namespace: nginx-space
```
ConfigMap
```yaml
apiVersion: v1
kind: ConfigMap
data:
name: nginx
dev: nginx-space
```
Transformed resource
```yaml
apiVersion: v1
kind: Deployment
metadata:
namespace: nginx-space # kpt-set: ${dev}
```
* Updates the create-setters docs accordingly.

create-setters: handle multiple lines and substrings

---

functions/go/search-replace/README.md
functions/go/search-replace/go.mod
functions/go/search-replace/go.sum
functions/go/search-replace/metadata.yaml
functions/go/search-replace/searchreplace/search_replace.go
functions/go/search-replace/searchreplace/search_replace_test.go
functions/go/search-replace/searchreplace/searchreplacecases_test.go
tests/search-replace/file-path-match/.expected/diff.patch
tests/search-replace/file-path-match/.expected/exec.sh
tests/search-replace/file-path-match/.krmignore
tests/search-replace/file-path-match/Kptfile
tests/search-replace/file-path-match/resources.yaml
tests/search-replace/file-path-match/setters.yaml
tests/search-replace/file-path-match/subpkg/Kptfile
tests/search-replace/file-path-match/subpkg/resources.yaml
tests/search-replace/file-path-match/subpkg/setters.yaml

This PR does following things:
1. Adds `by-file-path` matcher to search-replace function. Using this option, users can target specific file(s).
2. Removes check for empty search criteria.
3. Update docs.
[golang](https://github.com/golang/go/issues/11862) [filepath.Match()](https://golang.org/pkg/path/filepath/#Match) doesn't support doublestar match. I used [doublestar](https://github.com/bmatcuk/doublestar) library for filepath expressions matching as it is popular in the community and is well documented.

by-file-path matcher for search-replace

---

functions/go/starlark/go.mod
functions/go/starlark/go.sum

We want to pick up the changes in https://github.com/kubernetes-sigs/kustomize/pull/4023
Otherwise, some metadata fields will be lost during decoding.

Use newer kyaml in starlark

---

scripts/function-release.sh
scripts/git-tag-parser.sh

Add support for longer format that matches the path,
so that it works with go get.
It can handle both the short and long format.
Ref: https://github.com/GoogleContainerTools/kpt/issues/1992

Update the release script

---

functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/starlark.go
tests/starlark/map-key-inline-comment/.expected/diff.patch
tests/starlark/map-key-inline-comment/.krmignore
tests/starlark/map-key-inline-comment/Kptfile
tests/starlark/map-key-inline-comment/app.yaml
tests/starlark/map-key-inline-comment/fn-config.yaml

fixes: https://github.com/GoogleContainerTools/kpt/issues/2438

fix: avoid roundtriping when passing objects to starlark fn

---

functions/ts/generate-folders/metadata.yaml

CI was failing with error `http://localhost:3001/master//README.md [x1] {404}`
That was because scripts/generate_catalog/generate_catalog.go generates site/catalog.json
without RemoteSourcePath for that function and in that case index.html generates
href = localhost:3001/master//README.md for the button 'Edit this page'.
This patch adds sourceURL, so now catalog.json should contain correct data.

Fix master branch CI

---

functions/go/apply-setters/applysetters/apply_setters.go
functions/go/apply-setters/applysetters/apply_setters_test.go
functions/go/apply-setters/main.go
tests/apply-setters/no-matches-error/.expected/config.yaml
tests/apply-setters/no-matches-error/.expected/results.yaml

Similar to search-replace, apply-setters function should not throw error for no input or no matches for setters. It should just log the message and exit.

apply-setters: Do not error for empty input and no matches

---

examples/fix-simple/.expected/diff.patch
examples/fix-simple/README.md
examples/set-project-id-advanced/.expected/diff.patch
examples/set-project-id-advanced/Kptfile
examples/set-project-id-simple/Kptfile
functions/go/fix/README.md
functions/go/fix/fixpkg/fix.go
functions/go/fix/generated/docs.go
functions/go/list-setters/listsetters/list_setters_test.go
functions/go/set-project-id/README.md
functions/go/set-project-id/generated/docs.go
functions/go/set-project-id/main.go
testdata/fix/nginx-v1/Kptfile
testdata/fix/nginx-v1/hello-world/Kptfile
testdata/fix/nginx-v1alpha2/Kptfile
testdata/fix/nginx-v1alpha2/hello-world/Kptfile

Now that #546 has been merged, we should update `set-project-id` to use the new version of `apply-setters` so that the following repro steps won't produce an error:
```sh
kpt pkg get https://github.com/GoogleCloudPlatform/blueprints@v0.3.0
cd blueprints/catalog/empty
kpt fn eval ./ --image gcr.io/kpt-fn/set-project-id:v0.1.0 --include-meta-resources -- 'project-id=some-value'
kpt fn render ./
```

Update apply-setters from v0.1 to v0.2

---

examples/starlark-inject-sidecar/fn-config.yaml
examples/starlark-set-namespace/fn-config.yaml
examples/starlark-validation/fn-config.yaml
functions/go/starlark/README.md
functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/starlark.go
tests/starlark/non-standard-features/.expected/diff.patch
tests/starlark/non-standard-features/.expected/results.yaml
tests/starlark/non-standard-features/.krmignore
tests/starlark/non-standard-features/Kptfile
tests/starlark/non-standard-features/app.yaml
tests/starlark/non-standard-features/fn-config.yaml

Enabled set, global reassign, recursion
LoadBindsGlobally has been deprecated, and it is not enabled. Ref: https://pkg.go.dev/go.starlark.net/resolve#pkg-variables
fixes: https://github.com/GoogleContainerTools/kpt/issues/2429

enable some non-standard features in starlark

---

examples/kubeval-simple/resources.yaml
functions/ts/kubeval/third_party/github.com/instrumenta/openapi2jsonschema/openapi2jsonschema/command.py

Fixes: https://github.com/GoogleContainerTools/kpt/issues/2511
Also update the baked-in openapi version to v1.20.10

fix: handle non-trivial apiVersion correctly

---

.github/workflows/ci.yaml

GitHub Actions lets you cancel builds when new commits are pushed, similar to Prow. In most cases you probably want CI results for new commits and don't care about older commits. More details [here](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency) if you are interested.
I saw this while iterating on my other PR https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/64 and multiple  CI jobs were running for +30m on old commits.

chore: cancel old commit CI for PRs

---

functions/go/set-annotations/annotations_transformer.go
functions/go/set-annotations/annotations_transformer_test.go
functions/go/set-annotations/go.mod
functions/go/set-annotations/go.sum
functions/go/set-annotations/main.go
tests/set-annotations/additional-annotations/.expected/diff.patch
tests/set-annotations/additional-annotations/.expected/results.yaml
tests/set-annotations/additional-annotations/.krmignore
tests/set-annotations/additional-annotations/Kptfile
tests/set-annotations/additional-annotations/fn-config.yaml
tests/set-annotations/additional-annotations/local-config.yaml
tests/set-annotations/additional-annotations/resources.yaml
tests/set-annotations/legacy-config/.expected/results.yaml
tests/set-annotations/local-config/.expected/results.yaml

This adds functionality to include the filepath, fieldpath, and
value for each set-annotation in the output. This behavior is
modeled after the behavior of apply-setters.
Issues: GoogleContainerTools/kpt#2448

Set annotations changed files output

---

contrib/examples/analyze-istio-simple/.expected/config.yaml
examples/generate-folders-resourcehierarchy-v1/.expected/config.yaml
examples/generate-folders-resourcehierarchy-v1/.expected/results.yaml
examples/generate-folders-resourcehierarchy-v2/.expected/config.yaml
examples/generate-folders-resourcehierarchy-v2/.expected/results.yaml
examples/kubeval-mount-schema/.expected/config.yaml
examples/kubeval-mount-schema/.expected/exec.sh
examples/kubeval-mount-schema/.expected/results.yaml

These tests were broken due to upstream changes. The stderr
output includes additional output which would be fragile to
capture in a test case, so the assertion is changed to
results.yaml.
The contrib test is being skipped for now pending further
investigation.

test: Fix e2e tests

---

scripts/generate_catalog/generate_catalog.go
site/index.html

Issue: GoogleContainerTools/kpt#2609
This adds a new catalog-v2.json endpoint which expands upon the previous catalog.json schema to also include the latest patch version for each major/minor function release. This is presented as a new endpoint in order to avoid breaking compatibility with existing consumers of the original endpoint, such as versions of kpt already in the wild.
Updates the catalog pages of the website to include the latest patch version in:
- The version dropdown for the function
- A new dynamically rendered latest image section

Site examples patch version

---

scripts/generate_catalog/generate_catalog.go
site/index.html

A recent change updated the website to use patch versions in the
dropdown. The site URL still uses the minor version, so the href
needs to continue using the minor version.

fix: Use minor version for version dropdown href

---

site/index.html

Contrib functions are under the /contrib path, so this corrects
the path used in the href for contrib function version dropdowns.

fix: Correct path in href for contrib fn dropdown

---

Makefile
scripts/update_function_docs/function_release.go
scripts/update_function_docs/git.go
scripts/update_function_docs/go.mod
scripts/update_function_docs/go.sum
scripts/update_function_docs/main.go
scripts/update_function_docs/update_function_docs.go

This script is intended to be used for updating the docs for
a provided release branch to reflect the latest patch version
of that release.
Issues: GoogleContainerTools/kpt#2609

Add script for updating function docs

---

scripts/update_function_docs/git.go

The prior implementation was resulting in redundant quotes in the
commit message.

fix: Remove quotes from generated commit messages

---

scripts/verify-docs.py

The documentation is being updated to specify the patch version
rather than the minor version in the package URLs. This change
will allow both minor/patch version to be specified in the
meantime. Once all the documentation has been updated, this
can be made more strict to only allow the latest patch version.

ci: Allow patch version for pkg url in verify-docs

---

functions/go/set-namespace/README.md
functions/go/set-namespace/namespace_transformer.go
functions/go/set-namespace/namespace_transformer_test.go
tests/set-namespace/ensure-name-substring/.expected/diff.patch
tests/set-namespace/ensure-name-substring/.krmignore
tests/set-namespace/ensure-name-substring/Kptfile
tests/set-namespace/ensure-name-substring/resources.yaml
tests/set-namespace/rolebindings/.expected/diff.patch
tests/set-namespace/rolebindings/.krmignore
tests/set-namespace/rolebindings/Kptfile
tests/set-namespace/rolebindings/resources.yaml

Issues: GoogleContainerTools/kpt#2397
This pull request adds support to update the namespace for
ServiceAccount resources which are referenced in the subjects
field of RoleBinding and ClusterRoleBinding resources.
Given a ServiceAccount with name sa-name is included in the
ResourceList, any RoleBinding or ClusterRoleBinding subject with
kind ServiceAccount and name sa-name will also have its namespace
set.
For the time being this functionality is being implemented in kpt
rather than the upstream kustomize library. If this behavior is
well received, it may be a future consideration to push this
functionality into kustomize.

Set namespace rolebinding behavior

---

thirdparty/kyaml/fnsdk/testutil/golden.go

Ref: https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/665#pullrequestreview-846955659
The test util need to better handling when to add these annotations or not. Alternatively, we can let the users control if add these annotations or not.
We will do that in the near future.

Don't add path and index annotation in golden test util

---

thirdparty/kyaml/fnsdk/testutil/golden.go

Reverts GoogleContainerTools/kpt-functions-catalog#725

Revert "Don't add path and index annotation in golden test util"

---

site/index.html

This change displays the latest image tag for the function in the
function doc page. This is intended as a convenience for users
to discover the full tag of the latest function image.
Issues: GoogleContainerTools/kpt#2320

docs: Dynamically render latest image tag in docs

---

functions/go/set-labels/go.mod
functions/go/set-labels/label_transformer.go
functions/go/set-labels/label_transformer_test.go
functions/go/set-labels/main.go
tests/set-labels/additional-labels/.expected/diff.patch
tests/set-labels/additional-labels/.expected/results.yaml
tests/set-labels/additional-labels/.krmignore
tests/set-labels/additional-labels/Kptfile
tests/set-labels/additional-labels/fn-config.yaml
tests/set-labels/additional-labels/local-config.yaml
tests/set-labels/additional-labels/resources.yaml
tests/set-labels/legacy-config/.expected/results.yaml
tests/set-labels/local-config/.expected/results.yaml

This adds functionality to include the filepath, fieldpath, and
value for each set-label in the output. This behavior is
modeled after the behavior of set-annotations.
An example output:
```
$ kpt fn render set-labels-advanced
Package "set-labels-advanced": 
[RUNNING] "gcr.io/kpt-fn/set-labels:unstable"
[PASS] "gcr.io/kpt-fn/set-labels:unstable" in 3.2s
Results:
[info] metadata.labels: set labels: {"color":"orange","fruit":"apple"}
[info] metadata.labels: set labels: {"color":"orange","fruit":"apple"}
[info] spec.selector.labels: set labels: {"color":"orange","fruit":"apple"}
Successfully executed 1 function(s) in 1 package(s).
```
This change is based on a change to bump the version of kustomize consumed by set-labels. That change has been proposed as a separate pull request here: …

Set labels changed files output

---

site/index.html

This updates the version dropdown to display the full version string,
e.g. v0.1.1 rather than 0.1.1
This is intended to make the versions displayed in the dropdown
consistent with the version used in tags.
Issues: https://github.com/GoogleContainerTools/kpt/issues/2320

docs: include v in version dropdown for site

---

contrib/functions/go/generate-kpt-pkg-docs/README.md
contrib/functions/go/generate-kpt-pkg-docs/docs/generate.go
contrib/functions/go/generate-kpt-pkg-docs/docs/generate_test.go
contrib/functions/go/generate-kpt-pkg-docs/docs/readme.go
contrib/functions/go/generate-kpt-pkg-docs/docs/resources.go
contrib/functions/go/generate-kpt-pkg-docs/docs/resources_test.go
contrib/functions/go/generate-kpt-pkg-docs/generated/docs.go
contrib/functions/go/generate-kpt-pkg-docs/main.go

This adds support for specifying an optional pkg name while generating documentation to support blueprint repo dir naming convention https://github.com/GoogleContainerTools/kpt/issues/2592. Also handles cases where a pkg may be empty.

feat(docs-fn): support explicit pkg name, handle empty pkg

---

examples/ensure-name-substring-depends-on/.expected/diff.patch
examples/ensure-name-substring-depends-on/.krmignore
examples/ensure-name-substring-depends-on/Kptfile
examples/ensure-name-substring-depends-on/README.md
examples/ensure-name-substring-depends-on/resources.yaml
functions/go/ensure-name-substring/README.md
functions/go/ensure-name-substring/ensure_name_substring.go
functions/go/ensure-name-substring/ensure_name_substring_test.go
functions/go/ensure-name-substring/go.mod
functions/go/ensure-name-substring/go.sum
functions/go/ensure-name-substring/main.go
functions/go/ensure-name-substring/metadata.yaml

The depends-on annotation can reference the name of other resources,
and this change makes sure that the name portion of such annotations
is properly handled by the ensure-name-substring function.
Issues: GoogleContainerTools/kpt#2579

feat: ensure-name-substring supports depends-on

---

CONTRIBUTING.md

After submitting https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/752 I realized that unstable is the intended tags for images on the master branch.  Now adding a note about it to guide the contributions.

additional contrib note

---

.github/workflows/release.yaml

This github action is intended to be run when a new release tag is
published with the form `functions/<lang>/<func>/<version>`.
It publishes a shorter tag for the same commit with the form
`<func>/<version>`. This is intended as a convenience and is needed for
the examples in the docs to function properly.
Issues: GoogleContainerTools/kpt#2704

ci: add github action for short release tags

---

Makefile
scripts/patch_reader/go.mod
scripts/patch_reader/go.sum
scripts/patch_reader/main.go
scripts/patch_reader/pkg/latestpatch/latestpatch.go
scripts/update_function_docs/function_release.go
scripts/update_function_docs/go.mod
scripts/verify-docs.py

Updates the verify-docs script to use the patch version for the Kptfile example checks.
The update_function_docs script currently sets the function tag in the Kptfile to the latest patch version, which is the expected behavior. This Kptfile check in verify-docs needs to be updated to allow the expected behavior to pass in CI.
The logic for parsing the latest patch version is moved to an independent module so that it can be reused by other scripts. A small CLI is added so that it can also be invoked by the verify-docs python script.

Verify docs kptfile patch version

---

scripts/patch_reader/pkg/latestpatch/latestpatch.go
scripts/update_function_docs/git.go

This change ensures the tags are fetched before parsing the list of
tags. This is needed because the tags are not currently fetched by the
verify-docs github action.

ci: fetch tags before getting latest patch version

---

scripts/update_function_docs/function_release.go

This change fixes the update-function-docs script to properly update the
sourceUrl field in the metadata.yaml file. This is done by using the
appropriate suffix for sourceUrl depending on whether it is a contrib
function.

fix: update-function-docs contrib sourceURL

---

functions/go/export-terraform/README.md
functions/go/export-terraform/terraformgenerator/terraform_generator.go
functions/go/export-terraform/testdata/iam/input/folder_ignored.yaml

Since Terraform is a clusterless service, the exported config should exclude any resources which are specific to Config Controller.
Context: b/225041968

fix: Skip clusterless resources in exported Terraform

---

scripts/docker.sh

On some versions of bash an error was being thrown due to the build_args
being interpreted as an unbound variable. This change adds a default
empty string value to the variable expansion so that this error does not
occur.
Issues: GoogleContainerTools/kpt#2902

fix: use default value for build args

---

examples/starlark-configmap-as-functionconfig/set-replicas.star

This PR was split out from https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/778, since https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/769 needs this PR while #778 is still blocked by another PR in the SDK repo.
Ref: changes in kpt: https://github.com/GoogleContainerTools/kpt/pull/2927

update the starlark configmap example to work with latest kpt

---

functions/go/apply-replacements/go.mod
functions/go/apply-replacements/go.sum
functions/go/apply-replacements/replacements/replacements.go

The function needs to return errors, otherwise kpt will assume the function executed successfully. 
Combined with https://github.com/GoogleContainerTools/kpt-functions-sdk/pull/534, this fixes https://github.com/GoogleContainerTools/kpt/issues/2901.
Before: 
```
Package "apply-replacements-error": 
[RUNNING] "gcr.io/kpt-fn/apply-replacements:unstable"
[PASS] "gcr.io/kpt-fn/apply-replacements:unstable" in 1.1s
Results:
[error]: nothing selected by Pod.[noVer].[noGrp]/my-po.[noNs]:spec
```
After:
```
Package "apply-replacements-error": 
[RUNNING] "gcr.io/kpt-fn/apply-replacements:unstable"
[FAIL] "gcr.io/kpt-fn/apply-replacements:unstable" in 1.1s
Results:
[error]: nothing selected by Pod.[noVer].[noGrp]/my-po.[noNs]:spec
Exit code: 1
```

[apply-replacements] return all function errors

---

functions/go/starlark/krmfn/krmfn.go
functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/loadlib.go
tests/starlark/load-library/.expected/diff.patch
tests/starlark/load-library/fn-config.yaml

This adds a builtin to the starlark runtime called `match_gvkn`. Example usage in the value propagation demo: https://github.com/natasha41575/rolebinding-replacement/blob/9c26aedae15c36dfe9912ffa9706b4d49288a1f2/starlark-and-replacements-function/generate-rolebinding-group.yaml#L14
This needs to be rebased on https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/778 for CI to pass (some dependency issues).
Some questions:
- What do we want to call the module? I named it "krmfn", but wondering should it be "fn" to be consistent with the go SDK?
- Eventually we are moving this code and the forked starlark lib here to the kpt-functions-sdk. If I should change the directory structure to make moving it easier, let me know. Or if we want to move it over first before making this …

[starlark] builtin match_gvkn function

---

scripts/generate_catalog/generate_catalog.go

It turned out https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/810 doesn't really fix the issue, but this PR should.

fix example path parsing issue in site gen

---

functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/context.go
tests/starlark/openapi/.expected/config.yaml
tests/starlark/openapi/.expected/exec.sh
tests/starlark/openapi/.krmignore
tests/starlark/openapi/app.yaml
tests/starlark/openapi/fn-config.yaml

Added a wrapper to enable lazy initialization for openapi schema.
The schema is parsed only when the script tries to read it.
When the starlark script doesn't need to read openapi, it saves 0.7s.

Optimize openapi parsing in starlark

---

scripts/update_function_docs/function_release.go

This change applies a fix to the update-function-docs script to properly
set github urls to the minor release version of the function, which
points to the release branch. This conforms to the expected format of
verify-docs.
The refGroup pattern needs to accept minor version in case the version
string has already been set to the minor version (which can happen due
to the replaceTags transform running first).

fix: properly set github urls to minor version

---

scripts/generate_catalog/generate_catalog.go

the `keywords` come from two  sources. One is the keywordpool match (original, described below),the other is the metadata "tags" excluding "mutator" and "validator". keyword from tag is reformatted to lower case, dash replace empty space.  like "Config Sync" as "config-sync"
The PR is aimed to add the function `types` and `keywords` to `https://catalog.kpt.dev/catalog-v2.json`, so as `kpt fn eval` can filter functions by `--types` and `--keywords` flags.  
Ideally, we want the "types" and "keywords" to be configurable fields in each function's metadata.yaml. like below 
```yaml
image: gcr.io/kpt-fn/set-namespace
description: Update namespace.
types:
- mutator # New!
keywords:
- namespace # New!
- some-custom-fields  # New!
tags:
- mutator
sourceURL: …
```

add keywords and types to function meta (catalog-v2.json)

---

functions/go/set-namespace/transformer/namespace.go
tests/set-namespace/ns-unset/.expected/results.yaml

Current set-namespace gives redundant message as below
```bash
Results:
[info]: namespace "example" updated to "example", 0 values changed
[info] : set image from example to example
```
The second line is per KubeObject level info and should be removed.

Cleanup `set-namespace` output message

---

functions/go/export-terraform/README.md
functions/go/export-terraform/terraformgenerator/resources.go
functions/go/export-terraform/terraformgenerator/templates/log-export.tf
functions/go/export-terraform/terraformgenerator/terraform.go
functions/go/export-terraform/terraformgenerator/terraform_generator.go
functions/go/export-terraform/terraformgenerator/terraform_generator_test.go
functions/go/export-terraform/testdata/log/input/bq.yaml
functions/go/export-terraform/testdata/log/input/iam.yaml
functions/go/export-terraform/testdata/log/input/projects.yaml
functions/go/export-terraform/testdata/log/input/pubsub.yaml
functions/go/export-terraform/testdata/log/input/storage.yaml
functions/go/export-terraform/testdata/log/tf/README.md
functions/go/export-terraform/testdata/log/tf/log-export.tf
functions/go/export-terraform/testdata/log/tf/projects.tf
functions/go/export-terraform/testdata/log/tf/variables.tf
functions/go/export-terraform/testdata/log/tf/versions.tf

This add support for converting KRM [log-export blueprints](https://github.com/GoogleCloudPlatform/blueprints/tree/main/catalog/log-export/org) to [Terraform blueprints](https://github.com/terraform-google-modules/terraform-google-log-export).

feat: support log export in export-terraform

---

.github/workflows/ci.yaml
CONTRIBUTING.md
Makefile
scripts/docker.sh
scripts/function-release.sh
scripts/go-function-release.sh
scripts/ts-function-release.sh

In the `build` target, we only build the matching one. This is because `docker buildx` doesn't support exporting an multi-arch image to local. And building multi-arch image locally is not useful for users and it's more time consuming.
In the `push` target, we build for both amd64 and arm64.
fixes: https://github.com/GoogleContainerTools/kpt/issues/2874
fixes: https://github.com/GoogleContainerTools/kpt/issues/2775

support building multi-arch image

---

hack/Dockerfile

We use Louhi in our release pipeline. It underneath uses GCB.
We use this Dockerfile to build an image that contains go toolchain and node runtime so that we can use it in GCB.

update Dockerfile used in the release pipeline

---

.github/workflows/ci.yaml
examples/render-helm-chart-kustomize-private-git/credentials.env
examples/render-helm-chart-kustomize-private-oci/password
functions/go/render-helm-chart/metadata.yaml
scripts/verify-docs.py

Related to https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/875
Writes the Secrets to the necessary files as a preprocessing step. I'm doing this separately from https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/875 because PRs from forks cannot access Github Secrets. So this needs to go in first, then https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/875 can use it.

preprocessing step for render-helm-chart private repo tests

---

functions/go/export-terraform/terraformgenerator/templates/log-export.tf
functions/go/export-terraform/testdata/log/tf/log-export.tf

This extends the terraform-export fn template to include `log_sink_writer_identity` for the log-bucket destination.

fix:adds log-sink writer id to the export-terraform fn

---

examples/generate-folders-resourcehierarchy-v3/.expected/diff.patch
examples/generate-folders-resourcehierarchy-v3/resource-hierarchy.yaml
functions/ts/generate-folders/examples/simple_v3_ns.yaml
functions/ts/generate-folders/src/generate_folders.ts
functions/ts/generate-folders/src/generate_folders_test.ts

This adds [depends-on](https://kpt.dev/reference/annotations/depends-on/) support for generate-folders - generated child folders will depend on parent folders when actuated via kpt live apply. Noticed ~40% decrease in actuation time with some of our published hierarchies like [bu](https://github.com/GoogleCloudPlatform/blueprints/tree/main/catalog/hierarchy/bu).

feat: add depends-on support for resource hierarchy

---

functions/go/set-labels/go.mod
functions/go/set-labels/go.sum
functions/go/set-labels/transformer/common.go
functions/go/set-labels/transformer/labels.go

Generic KRM functions should be importable by other functions.
This PR updates the `set-labels` function to use the common const vars defined in go SDK, and makes its own functionConfig type const vars public.

fix: Make `set-labels` function configs importable 

---

functions/go/set-labels/run.go
functions/go/set-labels/run_js.go
functions/go/set-namespace/main.go
functions/go/set-namespace/run.go
functions/go/set-namespace/run_js.go

How to compile:
```
$ cd functions/go/set-namespace
$ GOOS=js GOARCH=wasm go build -o set-namespace.wasm 
```

support compiling set-ns and set-labels to wasm

---

RELEASING.md

We cannot hard reset the git references since it will confuse the local git cache and causes git ref conflict.
Here's the error I get https://linuxpip.org/git-error-cannot-lock-ref. I think running the `RELEASE_BRANCH=${RELEASE_BRANCH} make update-function-docs` the first time works, but after that, the git ref becomes dirty and hard to fix. 
Propose a safer way to run the doc-update script. I tried this new pattern to release `set-namespace:v0.4.1`, `apply-replacements:v0.1.1` and `starlark:v0.4.3`.

fix: Update RELEASE.md

---

functions/go/export-terraform/README.md
functions/go/export-terraform/terraformgenerator/templates/network.tf
functions/go/export-terraform/terraformgenerator/terraform.go
functions/go/export-terraform/terraformgenerator/terraform_generator.go
functions/go/export-terraform/testdata/multi-network/tf/network.tf
functions/go/export-terraform/testdata/network/input/routes.yaml
functions/go/export-terraform/testdata/network/tf/network.tf

This adds support for exporting ComputeRoute.
b/243555859

feat: support routes in export-terraform

---

functions/go/remove-local-config-resources/go.mod
functions/go/set-enforcement-action/go.mod
scripts/generate_catalog/go.mod
scripts/update_function_docs/go.mod

This was causing some IDE warnings.

Fix some incorrect/duplicate go.mod paths

---

build/docker/ts/defaults.env
functions/ts/kubeval/build/kubeval.Dockerfile
scripts/docker.sh

The defaults file is intended for generic default values that can be
shared for Dockerfiles across multiple functions. In this case
KUBEVAL_BUILDER_IMAGE is specific to the kubeval function and can simply
be defined in the dockerfile for that function.

remove KUBEVAL_BUILDER_IMAGE from generic defaults

---

examples/render-helm-chart-kustomize-values-files/README.md
functions/go/render-helm-chart/third_party/sigs.k8s.io/kustomize/api/builtins/HelmChartInflationGenerator.go

From discussion in https://kubernetes.slack.com/archives/C0155NSPJSZ/p1666107163910269
Add example for `render-helm-chart` of remote chart with local values file. Also improve the error message when the local file is not available.

`render-helm-chart`: add example with local values files and fix error message

---

.github/workflows/firebase-hosting-merge.yml

this "merge gob" is removed in https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/940/files, which is aimed at discontinuing the development of those functions that  are out of the current repo. 
However, `preview-hierarchy` function  (from GOB) has been released and the "Doc deployment" GitHub action" requests the existence of the  `preview-hierarchy` source code (achieved from "merge gob").
As a quick fix to "Doc deployment", this PR adds back the "merge gob" step.
In the long term, we should only support the functions whose source code is in the kpt-functions-catalog repo, and not mirror the external repos.

fix: Revert the Gob cleanup for `preview-hierarchy` function

---

examples/render-helm-chart-crds/README.md
examples/render-helm-chart-kustomize-inline-values/README.md
examples/render-helm-chart-kustomize-private-git/README.md
examples/render-helm-chart-kustomize-private-oci/README.md
examples/render-helm-chart-kustomize-values-files/README.md
examples/render-helm-chart-local/README.md
examples/render-helm-chart-remote-values-file/README.md
examples/render-helm-chart-remote/README.md
functions/go/render-helm-chart/README.md

release render-helm-charts v0.2 for private repo authentication and OCI support

docs: Update tags for go/render-helm-chart/v0.2.0 (#879)

---

functions/go/Makefile

We explored using ko to build and push functions. Affected functions include `set-name-prefix`, `bind` `set-gcp-resource-ids`. 
We want to leverage the current louhi release pipeline  to release these `ko` built functions as an experimental approach.  
This PR adds the `set-name-prefix` to the release workflow (verified in my own repo, exclude multi-platform dockerx). Some additional tagging changes might be needed, and I'll do that in a follow-up PR. But I'd like to have this change take effect to the workflow as the first step.

feat: Include ko push for set-name-prefix fn

---

functions/go/bind/Makefile
functions/go/set-gcp-resource-ids/Makefile
functions/go/set-name-prefix/Makefile

fix louhi release pipeline which does not have `gcloud` installed in its build image. https://louhi.dev/?projectId=5662083073179648#/execution-detail/6327051601313792

fix: make 'gcloud' as optional in Makefile for ko push

---

.github/hooks/pre-commit

In particular, the backticks around make generate would try to run
make generate!

Update precommit hook to pass shellcheck

---

scripts/generate_catalog/generate_catalog.go

This allows the site to be generated successfully. Currently `site-generate` make command fails with `Error getting metadata for "set-name-prefix" from "remotes/origin/set-name-prefix/v0.0"` preventing the CI `Generate Site` step from completing successfully.

Skip set-name-prefix branch when generating the function catalog

---

functions/go/apply-replacements/README.md

Fixes the external link on the apply replacements function documentation in reference to  GoogleContainerTools/kpt/issues/3594.

Fix external link on apply replacements documentation

---

site/sidebar.md

This pull request brings the site sidebar back into sync with the kpt.dev sidebar.

Update site sidebar with gitops and guides links

---

site/index.html

This pull request programmatically adds the external link target to all external links on the [Functions Catalog site](https://catalog.kpt.dev/) to resolve GoogleContainerTools/kpt/issues/3594.

Allow navigation to external links in function catalog site

---

.github/workflows/after-push-to-branch.yaml
.github/workflows/after-tag-with-version.yaml
dev/cd/after-push-to-branch
dev/cd/after-tag-with-version
functions/go/set-name-prefix/Makefile
functions/go/set-name-prefix/krm-fn-metadata.yaml

We create some simple scripts that aim to support a reasonable CD process.
* On each push to the master branch, we push every function at that version.
* On each tag, we match that to a function directory and push that to
the container repo.  As with kpt functions, the format is:
`<directory path>/<version>`
The goal is that github actions should bind variables like IMAGE_REPO
and GIT_REF to the correct version, but otherwise we try to minimize
the amount of work we do in github actions.  Most of the logic should
be in a script in `dev/cd/`, that clearly corresponds to the trigger
(e.g. `after-branch-push` for pushes to the main branch,
`after-tag-push` for when a tag is pushed).
If we need to run in other CI/CD systems, it should suffice to hook up
the trigger to the same scripts under …

Create build scripts that are compatible with github actions (and others)

---

functions/go/starlark/main.go
functions/go/starlark/run.go
functions/go/starlark/run_js.go

Like https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/898 and https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/911 - this PR adds wasm functionality to the starlark function.
I validated the working of this function by running the examples from https://catalog.kpt.dev/starlark/v0.4/ (bottom of the page), and compare the output of the current function with a manually compiled and pushed version.

convert starlark to wasm

---

functions/go/render-helm-chart/Dockerfile

Just been using the updated `render-helm-chart` version just released in https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/1024 (Thanks for the super fast turnaround on this btw!)
I ran into some version issues in the traefik chart and noticed the helm version could do with an update https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/deployment.yaml#L2 |

updating helm to 3.11

---

functions/go/starlark/go.mod
functions/go/starlark/go.sum

Fix https://github.com/GoogleContainerTools/kpt/issues/3865
Update Starlark to include recent capability such as dictionary concatenation: https://github.com/google/starlark-go/pull/397

feat: update to Starlark v0.0.0-20230302034142-4b1e35fe2254

---

dev/cd/after-push-to-branch

Fixes https://github.com/GoogleContainerTools/kpt/issues/3864
It appears `after-push-to-branch` is failing as IMAGE_REPO includes uppercase
```
Error: error creating publisher: failed to parse "ghcr.io/GoogleContainerTools/kpt-functions-catalog" as repository: repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: GoogleContainerTools/kpt-functions-catalog
```

fix: ensure IMAGE_REPO is lowercase

---

RELEASING.md

The tag matters and has to be `functions/{language}/{function-name}/{semver}` to trigger the github action "release", specifically [this line of code](https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/.github/workflows/release.yaml#L33), which then triggers other tag based GitHub actions. 
This change is verified in starlark/v0.5.0 release.

Fix a bug in RELEASING tag

---

functions/go/starlark/starlark/config.go

Hi, I am browsing the starlark function code and found a typo and fixed it. I am sure there are no similar errors. @yuwenma

fix: typo stalark -> starlark

---

functions/go/Makefile
functions/go/apply-setters/Makefile
functions/go/apply-setters/krm-fn-metadata.yaml

Begin the process of migrating the krm fn images to ghcr.
Following the same pattern as - https://github.com/kptdev/krm-functions-catalog/tree/master/functions/go/set-name-prefix

Publish apply-setters image to ghcr

---

functions/ts/kubeval/README.md

kubeval project is no longer supported; the link now goes to a sketchy site 
longer-term, this whole page should probably be reevaluated

remove kubeval link

---

.github/actions/extract-tag-info/action.yaml
.github/workflows/after-push-to-branch.yaml
.github/workflows/after-tag-with-version.yaml
contrib/functions/go/Makefile
functions/go/Makefile

Update the existing gh action to trigger a tagged image push to ghcr when a new git tag is created during the Release process.

Add release tag gh action
